# Generated by Django 2.1.5 on 2019-01-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LrpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, null=True)),
                ('plate', models.CharField(max_length=255, null=True)),
                ('frame', models.IntegerField(null=True)),
            ],
        ),
    ]
